services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eg-r2-laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - eg-r2-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: eg-r2-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - eg-r2-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: eg-r2-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-laravel}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - eg-r2-network

volumes:
  mysql_data:
    driver: local

networks:
  eg-r2-network:
    driver: bridge